# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about teaching GitHub
baseurl: "/curly-more" # the subpath of your site, e.g. /blog
url: "https://wbrianleonard.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: W Brian Leonard
user_description: Anon Developer at Lorem Ipsum Dolor
user_title: Anon Developer
email: trainingdemos+wbleonard@github.com
twitter_username: brianleonard
github_username:  wbleonard
gplus_username:  lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
